import type { LocalClient, Project, Location, Item, Evidence } from '../dexie'

const NOW = new Date()
export const CLIENT_ID = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a10'
export const PROJECT_ID = 'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22'
export const TECHNICIAN_ID = 'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33'

export const mockClients: LocalClient[] = [
  {
    id: CLIENT_ID,
    name: 'Condomínio Residencial Fonte dos Pássaros',
    phone: '(11) 3384-0369',
  },
]

export const mockProjects: Project[] = [
  {
    id: PROJECT_ID,
    name: 'Condomínio Residencial Fonte dos Pássaros',
    street: 'Rua da Fonte',
    number: '275',
    complement: 'Blocos A e B',
    neighborhood: 'Perdizes',
    city: 'São Paulo',
    state: 'SP',
    postalCode: '05001-000',
    description: 'Vistoria baseada em laudo real: Blocos A, B e áreas externas.',
    clientId: CLIENT_ID,
    responsibleProfileId: TECHNICIAN_ID,
    totalArea: 12500,
    documentType: 'PT_APPROVED',
    documentStoragePath: null,
    status: 'in_progress',
    downloadState: 'device',
    updateState: 'updated',
    completedItems: 0,
    totalItems: 6,
    createdAt: NOW,
    downloadedAt: NOW,
    syncedAt: NOW,
    serverUpdatedAt: NOW,
  },
]

export const mockLocations: Location[] = [
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    projectId: PROJECT_ID,
    name: 'Térreo - Hall de Entrada',
    type: 'floor',
    deletedAt: null,
    updatedAt: new Date('2024-01-01T10:00:00Z'),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    projectId: PROJECT_ID,
    name: 'Área Externa',
    type: 'outdoor',
    deletedAt: null,
    updatedAt: new Date('2024-01-01T10:00:00Z'),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    projectId: PROJECT_ID,
    name: 'Bloco A - 9º Andar',
    type: 'floor',
    deletedAt: null,
    updatedAt: new Date('2024-01-01T10:00:00Z'),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    projectId: PROJECT_ID,
    name: 'Escadas',
    type: 'other',
    deletedAt: null,
    updatedAt: new Date('2024-01-01T10:00:00Z'),
  },
  {
    id: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    projectId: PROJECT_ID,
    name: 'Portaria',
    type: 'room',
    deletedAt: null,
    updatedAt: new Date('2024-01-01T10:00:00Z'),
  },
]

export const mockItems: Item[] = [
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b01',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a01',
    description: '[IT-17] Ausência de mangueira de incêndio de 1.1/2" no abrigo',
    category: 'other',
    status: 'irregular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b02',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a02',
    description: '[IT-22] Abrigo inexistente para os 4 cilindros de GLP P-190Kg',
    category: 'other',
    status: 'irregular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b03',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    description: '[IT-15] Extintores de Pó BC e Água Pressurizada',
    category: 'extinguisher',
    status: 'regular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b04',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a03',
    description: '[IT-11] Fixar corretamente a luminária autônoma no teto',
    category: 'lighting',
    status: 'irregular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b05',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a05',
    description: '[IT-13] Realizar o endereçamento dos dispositivos na central digital',
    category: 'alarm',
    status: 'irregular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
  {
    id: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b06',
    projectId: PROJECT_ID,
    locationId: 'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380a04',
    description: '[IT-10] Corrimãos descontínuos e ausência de fitas antiderrapantes',
    category: 'emergency_exit',
    status: 'irregular',
    deletedAt: null,
    deletedById: null,
    updatedAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
    conflictStatus: false,
    conflictRemoteStatus: null,
  },
]

export const mockEvidence: Evidence[] = [
  {
    id: 'f0eebc99-9c0b-4ef8-bb6d-6bb9bd380c01',
    itemId: 'e0eebc99-9c0b-4ef8-bb6d-6bb9bd380b01',
    type: 'comment',
    blob: null,
    storagePath: null,
    comment:
      'Foi constatado durante vistoria técnica prévia que a caixa estava vazia e lacre rompido.',
    createdAt: NOW,
    technicianId: TECHNICIAN_ID,
    syncedAt: NOW,
  },
]
